// The Resource Library — a wiki/manifest of every file that built this
// Command Center. Authored 2026-07-06. This catalog is self-describing: it
// lists the primary source materials, the mined data files, the media assets,
// the site sections, and the build scaffold — and cross-links them so any
// resource points to where it came from and where it lands.

export type ResourceKind = 'source' | 'data' | 'media' | 'section' | 'build'

export interface Resource {
  id: string
  name: string
  path: string // repo path or the real-world origin
  kind: ResourceKind
  group: string // display heading
  what: string
  provenance?: string // where it came from
  size?: string
  href?: string // served URL (media only) — opens the actual file
  section?: string // nav id, for kind 'section'
  feeds?: string[] // section nav ids a data/media file supplies
  builtFrom?: string[] // resource ids a section consumes
}

// Section id → label, mirrored from App.tsx so links stay in sync.
export const sectionLabels: Record<string, string> = {
  brand: 'Brand Strategy',
  doorway: 'The Doorway',
  storyline: 'The Storyline',
  overview: 'The Shoot',
  clips: 'Clip Library',
  quotes: 'Quote Wall',
  themes: 'Themes',
  arcs: 'Arcs',
  physical: 'Physical Layer',
  vault: 'Image Vault',
  calls: 'Call Vault',
  ideas: 'Idea Bank',
  youtube: 'YouTube',
  linkedin: 'LinkedIn',
  vlog: 'Personal Vlog',
  email: 'Email Spine',
  workflow: 'Edit Workflow',
  calendar: '4-Month Plan',
  resources: 'Resource Library',
}

// ————— MEDIA FILE LISTS (verified against /public) —————
export const frameFiles: string[] = [
  'poster.png', 't00300.jpg', 't02100.jpg', 't03900.jpg', 't05700.jpg',
  't07500.jpg', 't09300.jpg', 't11100.jpg', 't12900.jpg', 't14700.jpg',
  't16500.jpg', 't18300.jpg', 't19800.jpg', 't20700.jpg', 't21300.jpg',
  't21800.jpg',
]

export const frames2Files: string[] = [
  't00060.jpg', 't00649.jpg', 't00845.jpg', 't01434.jpg', 't01631.jpg',
  't02613.jpg', 't03202.jpg', 't04381.jpg', 't04577.jpg', 't04774.jpg',
  't05756.jpg', 't05952.jpg', 't06542.jpg', 't07720.jpg', 't08899.jpg',
  't09292.jpg',
]

export const picFiles: string[] = [
  'IMG_1227.jpeg', 'IMG_1241.jpeg', 'IMG_1248.jpg', 'IMG_1270.jpeg',
  'IMG_1337.jpeg', 'IMG_1338.jpeg', 'IMG_1348.jpeg', 'IMG_1356.jpeg',
  'IMG_1361.jpeg', 'IMG_1370.jpeg', 'IMG_1373.jpeg', 'IMG_1374.jpeg',
  'IMG_1375.jpeg', 'IMG_1376.jpeg', 'IMG_1377.jpeg', 'IMG_1378.jpeg',
  'IMG_1379.jpeg', 'IMG_1380.jpeg', 'IMG_1382.jpeg', 'IMG_1383.jpeg',
  'IMG_1384.jpeg', 'IMG_1385.jpeg', 'IMG_1386.jpeg', 'IMG_1387.jpeg',
  'IMG_1388.jpeg', 'IMG_1389.jpeg', 'IMG_1390.jpeg', 'IMG_1391.jpeg',
  'IMG_1392.jpeg', 'IMG_1393.jpeg', 'IMG_1394.jpeg', 'IMG_1395.jpeg',
  'IMG_1396.jpeg', 'IMG_1397.jpeg', 'IMG_1398.jpeg', 'IMG_1399.jpeg',
  'IMG_1400.jpeg', 'IMG_1401.jpeg', 'mov_1.jpg', 'mov_2.jpg', 'mov_3.jpg',
]

export const resources: Resource[] = [
  // ═══════════════ PRIMARY SOURCE MATERIALS ═══════════════
  {
    id: 'src-transcript',
    name: 'transcript-6-21-26.txt',
    path: 'analysis/transcript-6-21-26.txt',
    kind: 'source',
    group: 'Primary Source Materials',
    what: 'The full 6h06m spoken transcript of the June 21, 2026 marathon shoot — the founding session this Command Center is mined from (joined 7.22 by the Session 2 transcript). Every session-1 clip, quote, theme, arc and plan traces back to a timestamp in this file.',
    provenance: 'Transcribed from the Frame.io master recording of the 6.21.26 shoot.',
    size: '308 KB · 6h 06m',
  },
  {
    id: 'src-mining',
    name: 'mining-result.json',
    path: 'analysis/mining-result.json',
    kind: 'source',
    group: 'Primary Source Materials',
    what: 'Raw structured output of the 22-agent analysis workflow that read the master transcript end-to-end and extracted the clips, shorts, pillar videos, quotes, themes, arcs, physical moments, and every platform strategy.',
    provenance: 'Generated by the 22-agent mining workflow over transcript-6-21-26.txt on 2026-07-05.',
    size: '412 KB',
  },
  {
    id: 'src-call-mining',
    name: 'call-mining-result.json',
    path: 'analysis/call-mining-result.json',
    kind: 'source',
    group: 'Primary Source Materials',
    what: 'Structured output from deep-mining the Call Recordings library — the receipts, stories, quotes and content pieces harvested from real client and founder calls.',
    provenance: 'A deep-mining agent read ~30 of the 168 highest-signal recordings (May 5–Jul 5, 2026) on 2026-07-05. The remaining calls are unmined backlog.',
    size: '179 KB',
  },
  {
    id: 'src-frameio',
    name: 'The Frame.io Master (Session 1)',
    path: 'External — Frame.io (h264_720 proxy)',
    kind: 'source',
    group: 'Primary Source Materials',
    what: 'The original 6h06m video of the shoot. Stills were pulled from it at ~30-minute intervals to become the frame library; its audio became the master transcript.',
    provenance: 'Recorded on the 6.21.26 shoot night.',
    size: '6h 06m video',
  },
  {
    id: 'src-transcript-s2',
    name: 'transcript-s2-7-22-26.txt',
    path: 'analysis/transcript-s2-7-22-26.txt',
    kind: 'source',
    group: 'Primary Source Materials',
    what: 'The full 2h36m timecoded transcript of Session 2 — the Heart Chapter (CR5E0001). Every session-2 clip, quote, theme, arc and calendar addition traces back to a timestamp in this file.',
    provenance: 'Camera-card transcript of the mid-July Thursday-night shoot; delivered alongside the 7.22.26 Frame.io upload and mined the same day.',
    size: '109 KB · 2h 36m',
  },
  {
    id: 'src-frameio-s2',
    name: 'The Frame.io Master (Session 2, "Pt. 2")',
    path: 'External — Frame.io share (Spencer M. Burnett Pt. 2, asset 4 of 4)',
    kind: 'source',
    group: 'Primary Source Materials',
    what: 'The 2h35m52s Session 2 master — the cards Q&A session shot at the playhouse desk with a homie feeding questions from behind the camera. Watched frame-by-frame (48-frame visual pass) for the physical layer; 16 stills pulled at the story beats into /frames2.',
    provenance: 'Shot on a Thursday night in mid-July 2026; uploaded to Frame.io 7.22.26 as "Spencer M. Burnett Pt. 2mp4.mp4" (1080p).',
    size: '2h 36m video',
  },
  {
    id: 'src-pics-folder',
    name: '~/Desktop/Pics',
    path: 'External — local photo folder',
    kind: 'source',
    group: 'Primary Source Materials',
    what: 'The photo folder holding the Crayon Deck (27 hand-drawn boards shot from one fixed overhead position), brand/merch assets, and set/lore stills. Copied into /public/pics and catalogued image-by-image.',
    provenance: 'Shot around the 6.21.26 session; broken down in album.ts on 2026-07-05.',
    size: '42 files',
  },
  {
    id: 'src-chris-call',
    name: '6/22 Conversation — Chris Douglas',
    path: 'External — call recording',
    kind: 'source',
    group: 'Primary Source Materials',
    what: '"Content Strategy and Bestowment Branding" — the 1:02–4:23am post-shoot conversation that the entire brand thesis (thesis, mission, dual tracks) was synthesized from.',
    provenance: 'Recorded 6/22/26; read end-to-end into brand.ts. Also draws on the 6/17 Wisdom Man brainstorm.',
  },
  {
    id: 'src-call-library',
    name: 'Call Recordings Library',
    path: 'External — 168 recordings',
    kind: 'source',
    group: 'Primary Source Materials',
    what: 'The full library of client, founder and strategy calls spanning May 5 – Jul 5, 2026 — the source pool for calls.ts and the two-month narrative arc.',
    provenance: '168 recordings in the window; ~30 highest-signal ones mined so far.',
    size: '168 recordings',
  },

  // ═══════════════ DATA FILES (the mined datasets) ═══════════════
  {
    id: 'data-content',
    name: 'content.ts',
    path: 'src/data/content.ts',
    kind: 'data',
    group: 'Data Files',
    what: 'The spine of the whole site. Holds clips, shorts, pillar videos, quotes, themes, arcs, physical moments, the YouTube / LinkedIn / vlog strategies, the edit workflow, the 4-month calendar, and the raw idea list. Since 7.22 it merges Session 2 (session2.ts) into every array.',
    provenance: 'Mined from the 6h06m master transcript by the 22-agent workflow (2026-07-05); Session 2 merge added 2026-07-22.',
    size: '~5,000 lines · 360+ KB',
    feeds: ['overview', 'clips', 'quotes', 'themes', 'arcs', 'physical', 'ideas', 'youtube', 'linkedin', 'vlog', 'workflow', 'calendar'],
  },
  {
    id: 'data-session2',
    name: 'session2.ts',
    path: 'src/data/session2.ts',
    kind: 'data',
    group: 'Data Files',
    what: 'The complete Session 2 mine — 46 clips (C81–C126), 14 shorts, 3 pillar assemblies, 54 quotes, 9 themes, 4 arcs, 16 physical moments and 20 raw ideas from the Heart Chapter, all tagged session: 2 and merged into content.ts.',
    provenance: 'Mined from transcript-s2-7-22-26.txt + a 48-frame visual pass on the Pt. 2 master, 2026-07-22.',
    size: '54 KB',
    feeds: ['overview', 'clips', 'quotes', 'themes', 'arcs', 'physical', 'ideas', 'youtube', 'linkedin', 'vlog', 'calendar'],
  },
  {
    id: 'data-calls',
    name: 'calls.ts',
    path: 'src/data/calls.ts',
    kind: 'data',
    group: 'Data Files',
    what: 'The two-month narrative arc plus receipts, call stories, call quotes, content pieces, clearance list and calendar additions harvested from real calls.',
    provenance: 'Mined from the Call Recordings library (May 5–Jul 5, 2026) on 2026-07-05.',
    size: '668 lines · 39 KB',
    feeds: ['calls', 'calendar'],
  },
  {
    id: 'data-album',
    name: 'album.ts',
    path: 'src/data/album.ts',
    kind: 'data',
    what: 'The image-by-image breakdown of the Pics folder — every photo’s family, what it is, its creative plays, and the month it lands in. Home of the Crayon Deck stop-motion concept.',
    group: 'Data Files',
    provenance: 'Authored from ~/Desktop/Pics on 2026-07-05.',
    size: '496 lines · 31 KB',
    feeds: ['vault'],
  },
  {
    id: 'data-brand',
    name: 'brand.ts',
    path: 'src/data/brand.ts',
    kind: 'data',
    group: 'Data Files',
    what: 'The personal brand strategy: the thesis ("Teaching magic. Literally."), the mission, and the dual mystical/technical tracks.',
    provenance: 'Synthesized from the 6/22 Chris Douglas conversation, the 6/17 Wisdom Man brainstorm, the crayon name-map board, and Spencer’s own articulation (7/6).',
    size: '197 lines · 17 KB',
    feeds: ['brand'],
  },
  {
    id: 'data-supplement',
    name: 'supplement.ts',
    path: 'src/data/supplement.ts',
    kind: 'data',
    group: 'Data Files',
    what: 'Gap-closing data authored after the adversarial-critic pass: the sticky-note index, thumbnail chain, clearance stage, team owners, email spine, content ledger, monthly KPIs, IG lane, and bonus post.',
    provenance: 'Authored to answer named holes in the mined outputs (2026-07-05).',
    size: '146 lines · 11 KB',
    feeds: ['physical', 'youtube', 'linkedin', 'email', 'workflow', 'calendar'],
  },
  {
    id: 'data-frames',
    name: 'frames.ts',
    path: 'src/data/frames.ts',
    kind: 'data',
    group: 'Data Files',
    what: 'The index of frame stills — each still’s file, timestamp, label and note — plus the poster note.',
    provenance: 'Stills pulled from the Frame.io master (h264_720 proxy) at ~30-minute intervals.',
    size: '99 lines · 4 KB',
    feeds: ['physical', 'overview'],
  },
  {
    id: 'data-types',
    name: 'types.ts',
    path: 'src/data/types.ts',
    kind: 'data',
    group: 'Data Files',
    what: 'The shared TypeScript interfaces (Clip, Quote, Theme, Arc, strategy shapes, calendar plan) that give every mined dataset a stable schema.',
    provenance: 'Defined alongside the mining workflow.',
    size: '117 lines',
    feeds: ['clips', 'quotes', 'themes', 'arcs', 'physical'],
  },
  {
    id: 'data-storyline',
    name: 'storyline.ts',
    path: 'src/data/storyline.ts',
    kind: 'data',
    group: 'Data Files',
    what: 'The dual-arc narrative: hero\'s-journey chapters (Ordinary World → The Second Witness), the four-track timeline (wizard / machine / clients / lore), and the told-stories canon — now including the Session 2 chapter, events, and four new parables.',
    provenance: 'Generated by the storyline workflow (Apr 1 → Jul 6) on 2026-07-06; Session 2 chapter and events added 2026-07-22.',
    size: '~750 lines · 55 KB',
    feeds: ['storyline'],
  },
  {
    id: 'data-ideas',
    name: 'ideasEnriched.ts',
    path: 'src/data/ideasEnriched.ts',
    kind: 'data',
    group: 'Data Files',
    what: 'The enriched Idea Bank: every idea with archetype, effort, impact, month, image, implementation steps and first action — including the eight Session 2 flagships (The Cards, Prayer Is Prompting, the Reality vs. Truth masterclass, Job Finished).',
    provenance: 'Generated by the idea-enrichment + storyline-ideation workflow (2026-07-06); Session 2 ideas added 2026-07-22.',
    size: '~3,550 lines · 210 KB',
    feeds: ['ideas'],
  },

  // ═══════════════ MEDIA ASSETS ═══════════════
  {
    id: 'media-frames',
    name: 'Frame Stills',
    path: 'public/frames/',
    kind: 'media',
    group: 'Media Assets',
    what: '16 stills pulled from the Frame.io master at ~30-minute intervals (denser across the final hour where the sticky notes come out), plus the poster. Indexed by frames.ts.',
    provenance: 'Extracted from the 6.21.26 Frame.io master.',
    size: '16 files',
    href: '/frames/poster.png',
    feeds: ['physical', 'overview'],
  },
  {
    id: 'media-frames2',
    name: 'Session 2 Frame Stills',
    path: 'public/frames2/',
    kind: 'media',
    group: 'Media Assets',
    what: '16 stills pulled from the Session 2 master at the story beats — the cards, the completion stillness, the download pose returning, the reading, the prayer posture, the arms-crossed wrap. Indexed by frames.ts (frames2).',
    provenance: 'Extracted from the 7.22.26 "Pt. 2" Frame.io master (1080p HLS) on 2026-07-22.',
    size: '16 files',
    href: '/frames2/t00060.jpg',
    feeds: ['physical', 'overview', 'storyline', 'ideas'],
  },
  {
    id: 'media-pics',
    name: 'The Pics Album',
    path: 'public/pics/',
    kind: 'media',
    what: '41 images — the 27-board Crayon Deck, brand/merch assets, and set/lore stills. Catalogued image-by-image in album.ts.',
    group: 'Media Assets',
    provenance: 'From ~/Desktop/Pics; shot around the 6.21.26 session.',
    size: '41 images',
    href: '/pics/IMG_1374.jpeg',
    feeds: ['vault'],
  },
  {
    id: 'media-acro',
    name: 'acro.mov',
    path: 'public/pics/acro.mov',
    kind: 'media',
    group: 'Media Assets',
    what: 'The motion clip surfaced in the Image Vault’s Motion family.',
    provenance: 'From ~/Desktop/Pics.',
    size: '3.8 MB video',
    href: '/pics/acro.mov',
    feeds: ['vault'],
  },

  // ═══════════════ SITE SECTIONS ═══════════════
  {
    id: 'sec-brand', name: 'Brand Strategy', path: 'src/sections/BrandStrategy.tsx', kind: 'section', group: 'Site Sections',
    section: 'brand', what: 'The thesis, mission and dual tracks that carry the brand.', builtFrom: ['data-brand'],
  },
  {
    id: 'sec-doorway', name: 'The Doorway', path: 'src/sections/Doorway.tsx', kind: 'section', group: 'Site Sections',
    section: 'doorway', what: 'The landing narrative — the way into the whole Command Center.', builtFrom: [],
  },
  {
    id: 'sec-storyline', name: 'The Storyline', path: 'src/sections/Storyline.tsx', kind: 'section', group: 'Site Sections',
    section: 'storyline', what: 'The chapters, timeline and told-stories that thread the year together.', builtFrom: ['data-storyline'],
  },
  {
    id: 'sec-overview', name: 'The Shoot', path: 'src/sections/Overview.tsx', kind: 'section', group: 'Site Sections',
    section: 'overview', what: 'The top-line yield of the night — everything the shoot produced at a glance.', builtFrom: ['data-content', 'data-frames'],
  },
  {
    id: 'sec-clips', name: 'Clip Library', path: 'src/sections/Clips.tsx', kind: 'section', group: 'Site Sections',
    section: 'clips', what: 'Every mined clip, short and pillar video with hooks and edit notes.', builtFrom: ['data-content', 'data-types'],
  },
  {
    id: 'sec-quotes', name: 'Quote Wall', path: 'src/sections/Quotes.tsx', kind: 'section', group: 'Site Sections',
    section: 'quotes', what: 'The pull-quote wall, each tagged by category, strength and use.', builtFrom: ['data-content', 'data-types'],
  },
  {
    id: 'sec-themes', name: 'Themes', path: 'src/sections/Themes.tsx', kind: 'section', group: 'Site Sections',
    section: 'themes', what: 'The recurring themes and what to develop each into.', builtFrom: ['data-content', 'data-types'],
  },
  {
    id: 'sec-arcs', name: 'Arcs', path: 'src/sections/Arcs.tsx', kind: 'section', group: 'Site Sections',
    section: 'arcs', what: 'The narrative arcs with beats, treatment and title ideas.', builtFrom: ['data-content', 'data-types'],
  },
  {
    id: 'sec-physical', name: 'Physical Layer', path: 'src/sections/Physical.tsx', kind: 'section', group: 'Site Sections',
    section: 'physical', what: 'The frame stills, sticky-note index and physical moments from the set.', builtFrom: ['data-frames', 'data-content', 'data-supplement', 'media-frames'],
  },
  {
    id: 'sec-vault', name: 'Image Vault', path: 'src/sections/ImageVault.tsx', kind: 'section', group: 'Site Sections',
    section: 'vault', what: 'The Pics album, filterable by family, with each image’s plays and slot.', builtFrom: ['data-album', 'media-pics', 'media-acro'],
  },
  {
    id: 'sec-calls', name: 'Call Vault', path: 'src/sections/CallVault.tsx', kind: 'section', group: 'Site Sections',
    section: 'calls', what: 'The receipts, stories and quotes mined from the call library.', builtFrom: ['data-calls'],
  },
  {
    id: 'sec-ideas', name: 'Idea Bank', path: 'src/sections/IdeaBank.tsx', kind: 'section', group: 'Site Sections',
    section: 'ideas', what: 'The enriched and raw idea backlog, sortable by impact and effort.', builtFrom: ['data-ideas', 'data-content'],
  },
  {
    id: 'sec-youtube', name: 'YouTube', path: 'src/sections/YouTubePlan.tsx', kind: 'section', group: 'Site Sections',
    section: 'youtube', what: 'The YouTube positioning, pillars, series and thumbnail chain.', builtFrom: ['data-content', 'data-supplement'],
  },
  {
    id: 'sec-linkedin', name: 'LinkedIn', path: 'src/sections/LinkedInPlan.tsx', kind: 'section', group: 'Site Sections',
    section: 'linkedin', what: 'The LinkedIn strategy, post types, weekly rhythm and ready posts.', builtFrom: ['data-content', 'data-supplement'],
  },
  {
    id: 'sec-vlog', name: 'Personal Vlog', path: 'src/sections/VlogPlan.tsx', kind: 'section', group: 'Site Sections',
    section: 'vlog', what: 'The personal vlog format and episode plan.', builtFrom: ['data-content'],
  },
  {
    id: 'sec-email', name: 'Email Spine', path: 'src/sections/EmailPlan.tsx', kind: 'section', group: 'Site Sections',
    section: 'email', what: 'The email sequence that spines the four months together.', builtFrom: ['data-supplement'],
  },
  {
    id: 'sec-workflow', name: 'Edit Workflow', path: 'src/sections/EditWorkflow.tsx', kind: 'section', group: 'Site Sections',
    section: 'workflow', what: 'The tools, pipeline, per-clip checklist, clearance stage and team owners.', builtFrom: ['data-content', 'data-supplement'],
  },
  {
    id: 'sec-calendar', name: '4-Month Plan', path: 'src/sections/Calendar.tsx', kind: 'section', group: 'Site Sections',
    section: 'calendar', what: 'The month themes, weekly focus, content ledger and monthly KPIs.', builtFrom: ['data-content', 'data-supplement', 'data-calls'],
  },
  {
    id: 'sec-resources', name: 'Resource Library', path: 'src/sections/ResourceLibrary.tsx', kind: 'section', group: 'Site Sections',
    section: 'resources', what: 'This page — the self-describing manifest of every file that built the Command Center.', builtFrom: ['data-resources'],
  },

  // ═══════════════ BUILD SCAFFOLD ═══════════════
  {
    id: 'data-resources', name: 'resources.ts', path: 'src/data/resources.ts', kind: 'build', group: 'Build Scaffold',
    what: 'The catalog powering this Resource Library — every source, data file, media asset, section and config entry.', size: 'this file',
  },
  {
    id: 'build-app', name: 'App.tsx', path: 'src/App.tsx', kind: 'build', group: 'Build Scaffold',
    what: 'The shell: the left-nav section registry, active-section state, and the navigation context the Resource Library links through.',
  },
  {
    id: 'build-ui', name: 'ui.tsx', path: 'src/components/ui.tsx', kind: 'build', group: 'Build Scaffold',
    what: 'Shared UI primitives — SectionHeader, Card, Fade, Tag, Timestamp, Stars — used by every section.',
  },
  {
    id: 'build-css', name: 'index.css', path: 'src/index.css', kind: 'build', group: 'Build Scaffold',
    what: 'The theme tokens (ink / bone / amber palette, Caveat + serif fonts) and custom classes (note-card, grain, thin scrollbar).',
  },
  {
    id: 'build-html', name: 'index.html', path: 'index.html', kind: 'build', group: 'Build Scaffold',
    what: 'The app shell — title, favicon (the shoot poster), and the React mount point.',
  },
  {
    id: 'build-main', name: 'main.tsx', path: 'src/main.tsx', kind: 'build', group: 'Build Scaffold',
    what: 'The React 19 entry point that mounts App.',
  },
  {
    id: 'build-config', name: 'Build Config', path: 'vite.config.ts · tsconfig.json · package.json', kind: 'build', group: 'Build Scaffold',
    what: 'The toolchain: Vite 6 + React 19 + Tailwind 4, TypeScript, framer-motion, lucide-react and @fontsource/caveat.',
  },
]
